# https://starship.rs/config/
# Setup: ~/.config/starship.toml
# Trigger update: source ~/.cache/starship/init.nu

[directory]
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = true

[gcloud]
symbol = "️🇬️ "
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '

[git_branch]
symbol = " "
truncation_length = 4
truncation_symbol = ""
ignore_branches = ["master", "main"]

[git_status]
conflicted = "🏳"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
up_to_date = "✓"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

# [hostname]
# ssh_only = false
# format = "[$ssh_symbol](bold blue) on [$hostname](bold red) "
# trim_at = ".companyname.com"
# disabled = false

[python]
symbol = "👾 "
pyenv_version_name = true
# Only use the `python3` binary to get the version.
python_binary = "python3"

# [status]
# style = "bg:blue"
# symbol = "🔴 "
# success_symbol = "🟢 SUCCESS"
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
# map_symbol = true
# disabled = false

[time]
disabled = false
format = '🕙 [\[ $time \]]($style) '
time_format = "(w%U.%a) %F %H:%M"
utc_time_offset = "+8"
time_range = "00:05:00-23:55:00"

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false
show_always = true
