apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: docker-image
build:
  artifacts:
    - image: asia-east1-docker.pkg.dev/qwiklabs-gcp-01-0cda8821429a/my-repo/locust-tasks
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s-manifests/master-controller.yaml
    - k8s-manifests/master-service.yaml
    - k8s-manifests/worker-controller.yaml
